### PR TITLE
add EV data for new pokemon

### PR DESCRIPTION
**Pull request by 2nd-player**
#9 also base stats of Alolan Raichu and Minior Core are now fixed.
sorry for my mistake.

### CODE REVIEW

**Comment by 2007heaven** [comment]
Hey there @2nd-player. Thanks for the contrib. 👍

However, Minior Core's spdef should be `60` instead of `80`; at least that's what [bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Minior_(Pok%C3%A9mon)) and [serebii](http://www.serebii.net/pokedex-sm/774.shtml) suggest.

A change in its value will make the pr good to merge. 😉

**Comment by 2nd-player** [comment]
I no longer able to believe my (eyes|brain).
If you nether, please check [precompressed data here](http://wiki.xn--rckteqa2e.com/w/index.php?curid=36137).

**Comment by 2007heaven** [comment]
Hahaaa! I know it can get weird when you're editing multiple values crammed together man, it's ok. Your new values are correct. 👌 

774.1 (core) from your link has `60` spdef too. ^^

Now, if only I had merge rights to this. 😇 @Arty2

**Comment by Arty2** [comment]
Oh thought I had granted these; will be away from comp for two-three days

͝н̵Π

**Comment by 2007heaven** [comment]
I see. The priv you're looking for should be `write access` or sth.

**Pull request merged**
